//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-1FGKC14\\SQLSERVER;Initial Catalog=I:\\LICENTA\\GESTSOFT\\DB\\SOFT" +
            "GEST.MDF;User ID=sa")]
        public string I__LICENTA_GESTSOFT_DB_SOFTGEST_MDFConnectionString {
            get {
                return ((string)(this["I__LICENTA_GESTSOFT_DB_SOFTGEST_MDFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-1FGKC14\\SQLSERVER;Initial Catalog=I:\\LICENTA\\GESTSOFT\\DB\\SOFT" +
            "GEST.MDF;Integrated Security=True")]
        public string FillListaFirme {
            get {
                return ((string)(this["FillListaFirme"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string utilizator_Logat {
            get {
                return ((string)(this["utilizator_Logat"]));
            }
            set {
                this["utilizator_Logat"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=|DataDirectory|\\SoftGest.mdf;Integra" +
            "ted Security=True;Connect Timeout=30")]
        public string SoftGestConnectionString {
            get {
                return ((string)(this["SoftGestConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-1FGKC14\\SQLSERVER;Initial Catalog=SoftManager;Persist Securit" +
            "y Info=True;User ID=sa;Password=wise2016")]
        public string SoftManagerConexiuneFinala {
            get {
                return ((string)(this["SoftManagerConexiuneFinala"]));
            }
        }
    }
}
